### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-js-functions-strings-variables#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://numerous-knot.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/js-functions-strings-variables/1) criteria:
- [x] an HTML profile with a name, favorite color, and at least one other attribute
- [x] the containing element for each attribute is blank initially
- [x] prompts are used to collect text values for each attribute
- [x] each attribute is given an `id` (e.g. "name", "favorite-color"), which is used to target that element (with [`document.getElementById`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById)) and set its [`innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) to the value provided by the user

**Comment by ackleyd1** [comment]
I added a bit of code to change the background color of div too, just for funsies

**Comment by chrisvfritz** [comment]
Nice touch with the background color! The only room for improvement I see are some format issues. They're nitpicks, but it's good to establish good habits now before we're working on huge codebases. :smiley: 

### Indentation

The indentation on [this line](https://github.com/ackleyd1/codelab-js-functions-strings-variables/blob/master/index.html#L14) isn't quite right.

### Spaces around `=` in JavaScript

[This line](https://github.com/ackleyd1/codelab-js-functions-strings-variables/blob/master/script.js#L4) and [this line](https://github.com/ackleyd1/codelab-js-functions-strings-variables/blob/master/script.js#L7) contains an assignment without a space on either side of the `=`. It's convention to include that space and especially since you're doing it on the first assignment, let's stay consistent.

**Comment by ackleyd1** [comment]
Fixed

**Comment by chrisvfritz** [comment]
Beautiful! :+1: :shipit:
